language: bash

services:
  - docker
  
os:
  - linux
  - osx
  - windows

script:
  - if [ "$TRAVIS_OS_NAME" == 'windows' ]; then docker pull --platform linux ubuntu:eoan; fi
  - docker build -t chown .