name: Docker

on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Reproduce Chown Problem
        run: ./scripts/build.sh

