name: Docker

on: [push]

jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker pull --platform linux ubuntu:eoan
      - name: Reproduce Chown Problem
        run: docker build -t chown .

    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Reproduce Chown Problem
        run: docker build -t chown .
